'use client'
import Head from 'next/head'
import { ReactNode } from 'react'

// ** Layout
import LayoutNotApp from 'src/views/layouts/LayoutNotApp'

export default function Home() {
  return (
    <>
      <Head>
        <title>Ecommerce CMS</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      {/* <Typography>Hello world!</Typography>
      <Box sx={{ margin: 6, width: '200px' }}>
        <CustomTextField id='outlined-multiline-flexible' label='Muitiline' />
      </Box> */}
    </>
  )
}

Home.getLayout = (page: ReactNode) => <LayoutNotApp>{page}</LayoutNotApp>
Home.guestGuard = true
Home.authGuard = true
